// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OarabileMarwane_CV.Data;

#nullable disable

namespace OarabileMarwane_CV.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("OarabileMarwane_CV.Models.CV.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOfCert")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CredentialId = "WMKQNK95FJB11JGM",
                            ExpiryDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameOfCert = "CompTIA A+",
                            Organisation = "CompTIA"
                        },
                        new
                        {
                            Id = 2,
                            CredentialId = "BSXTSTDRDJ4E159B",
                            ExpiryDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameOfCert = "CompTIA Network+",
                            Organisation = "CompTIA"
                        });
                });

            modelBuilder.Entity("OarabileMarwane_CV.Models.CV.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Linkedin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("avatar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutMe = "I am currently in my final year of studying a Bachelor of Computer and Information Sciences in Application Development at Emeris Ruimsig – Johannesburg Campus. \r\nI am excited about the challenges and knowledge that will be presented to me this year as I pursue a career as a software developer and, later on, a project manager.\r\n\r\nI also have a passionate backup interest in Technical Support, in terms of building and maintaining devices used in our day-to-day. If becoming a software engineer doesn’t work out, I would love being Technical Support to improve user experiences,",
                            Email = "oarabile.marwane1@gmail.com",
                            FirstName = "Oarabile",
                            LastName = "Marwane",
                            Linkedin = "https://www.linkedin.com/in/oarabile-marwane-544478261/",
                            Location = "Gauteng",
                            PhoneNumber = "+27 66 2242737",
                            Title = "3rd Year Student in Bachelor of Computer and Information Science In Application Development Student | Emeris Ruimsig",
                            avatar = "/assets/images/ohAHandsomGuy.png"
                        });
                });

            modelBuilder.Entity("OarabileMarwane_CV.Models.CV.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = "Bachelor of Computer and Information Sciences in Application Development ",
                            Descrip = "This qualification has been designed to develop my ability to design, implement, and manage solutions for systemic thinkers, enabling me to develop software solutions for any device or platform in the South African economy.",
                            EndDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstitutionName = "Emeris Ruimsig",
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Degree = "Further Education and Training Certificate: Information Technology: Technical Support ",
                            Descrip = "Purpose of this qualification is to build a foundational entry into the field of Computer Sciences and Information Technology, specifically into the field of Systems Support, covering basic knowledge needed for further study in the field of Systems Support at Higher Education Levels.",
                            EndDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstitutionName = "CURRO HOLDINGS LTD ",
                            StartDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OarabileMarwane_CV.Models.CV.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Curro Holdings Ltd",
                            EmploymentType = "Full Time",
                            EndDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobDescription = "Providing a variety of support services to users of IT, with limited supervision and direction of others.\r\nContributing to solving user technical problems and meeting their support needs.",
                            JobTitle = "IT Learnership",
                            StartDate = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OarabileMarwane_CV.Models.CV.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A chatbot built in C# with NLP and task manager.",
                            GitHubLink = "https://github.com/MarwaneOarabile/CyberBot_ST10436124.git",
                            Name = "Cybersecurity Awareness Bot"
                        });
                });

            modelBuilder.Entity("OarabileMarwane_CV.Models.CV.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillDescp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SkillDescp = "Communicate effectively with fellow IT staff & users of information systems"
                        },
                        new
                        {
                            Id = 2,
                            SkillDescp = "Demonstrate an understanding of different types of computer systems and the use of computer technology in business."
                        },
                        new
                        {
                            Id = 3,
                            SkillDescp = "Hardware and Infrastructure Support for Personal Computers"
                        },
                        new
                        {
                            Id = 4,
                            SkillDescp = "Data Communications and Network Support"
                        },
                        new
                        {
                            Id = 5,
                            SkillDescp = "Design software applications on a variety of platforms"
                        },
                        new
                        {
                            Id = 6,
                            SkillDescp = "Communicate effectively and professionally as a member of a software design and development team."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
